### ISSUE TITLE
The write-component fails when using a lambert_conformal coordinate system in the southern hemisphere

### ISSUE THREAD

**Issue by gsketefian** [ufs-community/regional_workflow#608]
# Description
When using a write-component grid of type "lambert_conformal" in the southern hemisphere, the forecast model hangs on Hera.

Need to create an issue in the ufs-weather-model repo to address this.

## Steps to Reproduce
The following custom ESGgrid + write-component grid configuration (in config.sh) will cause a failure:

```
GRID_GEN_METHOD="ESGgrid"
QUILTING="TRUE"

ESGgrid_LON_CTR="166.0"
ESGgrid_LAT_CTR="-37.0"

ESGgrid_DELX="3000.0"
ESGgrid_DELY="3000.0"

ESGgrid_NX="420"
ESGgrid_NY="300"

ESGgrid_WIDE_HALO_WIDTH="6"

DT_ATMOS="45"

LAYOUT_X="16"
LAYOUT_Y="10"

BLOCKSIZE="32"

WRTCMP_write_groups="1"
WRTCMP_write_tasks_per_group=$(( 1*${LAYOUT_Y} ))

WRTCMP_output_grid="lambert_conformal"

WRTCMP_cen_lon="${ESGgrid_LON_CTR}"
WRTCMP_cen_lat="${ESGgrid_LAT_CTR}"

WRTCMP_stdlat1="${ESGgrid_LAT_CTR}"
WRTCMP_stdlat2="${ESGgrid_LAT_CTR}"

WRTCMP_dx="${ESGgrid_DELX}"
WRTCMP_dy="${ESGgrid_DELY}"

WRTCMP_nx="399"
WRTCMP_ny="285"

WRTCMP_lon_lwr_left="159.26"
WRTCMP_lat_lwr_left="-40.0"
```

Changing this domain (including the write-component grid) to be in the northern hemisphere works.

## Additional Context
This was first noticed by Iman Soltanzadeh during the UFS SRW App training during the week of 20210920 when he tried to run a custom regional domain over New Zealand.  It failed on Cheyenne, where the code crashes with an error in one of the ESMF subroutines.  I (@gsketefian) reproduced the failure on Hera, where the code hangs.

**Comment by mkavulich** [comment]
This issue no longer occurs in the latest version of the workflow/app. I have successfully run a southern-hemisphere lambert-conformal domain over New Zealand, data can be seen on Hera in /scratch2/BMC/gsd-fv3-dev/kavulich/UFS/test_southern_hemisphere/expt_dirs/test_southern_hemisphere. Here are the settings used for posterity:

## Added section in ush/predef_grid_params.yaml:
```
#-----------------------------------------------------------------------
#
# The RRFS CONUS domain with ~25km cells in southern hemisphere.
#
#-----------------------------------------------------------------------
#
"RRFS_CONUS_25km_SH":
  GRID_GEN_METHOD: "ESGgrid"
  ESGgrid_LON_CTR: -177.5
  ESGgrid_LAT_CTR: -38.5
  ESGgrid_DELX: 25000.0
  ESGgrid_DELY: 25000.0
  ESGgrid_NX: 219
  ESGgrid_NY: 131
  ESGgrid_PAZI: 0.0
  ESGgrid_WIDE_HALO_WIDTH: 6
  DT_ATMOS: 40
  LAYOUT_X: 5
  LAYOUT_Y: 2
  BLOCKSIZE: 40
  QUILTING:
    WRTCMP_write_groups: 1
    WRTCMP_write_tasks_per_group: 2
    WRTCMP_output_grid: "lambert_conformal"
    WRTCMP_cen_lon: -177.5
    WRTCMP_cen_lat: -38.5
    WRTCMP_stdlat1: -38.5
    WRTCMP_stdlat2: -38.5
    WRTCMP_nx: 217
    WRTCMP_ny: 128
    WRTCMP_lon_lwr_left: 152.719528
    WRTCMP_lat_lwr_left: -51.138123
    WRTCMP_dx: 25000.0
    WRTCMP_dy: 25000.0
```

And the config.yaml used for the test:
```
metadata:
  description: >-
    Sample community config
user:
  RUN_ENVIR: community
  MACHINE: hera
  ACCOUNT: fv3lam
platform:
  MODEL: FV3_GFS_v16_CONUS_25km
  MET_INSTALL_DIR: path/to/MET
  METPLUS_PATH: path/to/METPlus
  CCPA_OBS_DIR: /path/to/processed/CCPA/data
  MRMS_OBS_DIR: /path/to/processed/MRMS/data
  NDAS_OBS_DIR: /path/to/processed/NDAS/data
workflow:
  EXPT_SUBDIR: test_southern_hemisphere
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '20190615'
  DATE_LAST_CYCL: '20190615'
  CYCL_HRS:
    - 18
  FCST_LEN_HRS: 12
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
workflow_switches:
  RUN_TASK_MAKE_GRID: true
  RUN_TASK_MAKE_OROG: true
  RUN_TASK_MAKE_SFC_CLIMO: true
  RUN_TASK_GET_OBS_CCPA: false
  RUN_TASK_GET_OBS_MRMS: false
  RUN_TASK_GET_OBS_NDAS: false
  RUN_TASK_VX_GRIDSTAT: false
  RUN_TASK_VX_POINTSTAT: false
  RUN_TASK_VX_ENSGRID: false
  RUN_TASK_VX_ENSPOINT: false
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: grib2
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  FV3GFS_FILE_FMT_LBCS: grib2
task_run_fcst:
  WTIME_RUN_FCST: 02:00:00
  QUILTING: true
  PREDEF_GRID_NAME: RRFS_CONUS_25km_SH
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
```

Attached images are 12-hour sfc pressure and u10 fields, no obvious problems/imbalances that would be expected from bad ICs:


![ncview pressfc](https://user-images.githubusercontent.com/12705538/191367520-a2564fd9-c865-42c5-bf60-a2f599ac285d.png)
![ncview ugrd10m](https://user-images.githubusercontent.com/12705538/191367551-54bfddc8-d78b-4140-a467-99395b43b880.png)
